# Generated by Django 3.2.6 on 2021-09-06 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date creation')),
            ],
            options={
                'verbose_name_plural': 'departements',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tel', models.CharField(max_length=25)),
                ('date_embauche', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date embauche')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_app.departement')),
            ],
            options={
                'verbose_name_plural': 'employers',
            },
        ),
    ]
